# Elastic Net

In this notebook we will explain the effect of Lasso, ridge and Elastic net on coefficents

In [13]:
import sys
#sys.path.append('../') #if unable to import, uncomment line before this and try again.
from IPython.display import display, Math, Latex
from src.finance_ml.data_preparation.data_preparation import DataLoader
from src.finance_ml.indicators.indicators import Indicators
from src.finance_ml.Elastic_Net.Elastic_net import RegressionAnalysis

import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
fname_USDBRL = 'FX/USDBRL_2020-04-07_2022-04-06.parquet'
N = 40000
ticker = 'USDBRL'
keep_cols = ['VOLUME', 'VW', 'OPEN', 'CLOSE', 'HIGHT', 'LOW', 't', 'TRANSACTIONS']

regression_analysis = RegressionAnalysis(data_file=fname_USDBRL, ticker=ticker, keep_cols=keep_cols)
regression_analysis.load_data()
regression_analysis.prepare_features()

In [4]:
# Ridge Regression
ridge_model = regression_analysis.train_ridge(alpha=10)
regression_analysis.display_results(ridge_model, "Ridge")

After Ridge, we have only 7 non-zero coefficients.


metrics
MAE   0.000649
MSE   0.000001
RMSE  0.001196

In [5]:
ridge_model.coef_

array([ 2.63603233e-05,  8.52179263e-02, -2.14090443e-02,  8.19645404e-02,
        7.09543023e-02,  1.26596204e-04,  2.63603233e-05])

Coefficents of Lasso model:

In [6]:
# Lasso Regression
lasso_cv_model = regression_analysis.train_lasso_cv(eps=0.01, n_alphas=100, cv=5)
regression_analysis.display_results(lasso_cv_model, "Lasso CV")

After Lasso CV, we have only 3 non-zero coefficients.


metrics
MAE   0.001998
MSE   0.000006
RMSE  0.002528

In [7]:
lasso_cv_model.coef_

array([ 0.00000000e+00,  2.14544983e-01,  0.00000000e+00,  5.43432191e-07,
        3.28541875e-06, -0.00000000e+00,  0.00000000e+00])

Coefficents of Elastic net model: Case 1: Best L1 Ratio and Case 2: Different L1 Ratio

In [8]:
# Elastic Net
elastic_model = regression_analysis.train_elastic_net_cv(l1_ratios=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)
regression_analysis.display_results(elastic_model, "Elastic Net")

After Elastic Net, we have only 3 non-zero coefficients.


metrics
MAE   0.000724
MSE   0.000002
RMSE  0.001301

In [9]:
elastic_model.coef_

array([-0.00000000e+00,  2.16490211e-01,  0.00000000e+00,  5.22591569e-06,
        3.86878322e-06,  0.00000000e+00, -0.00000000e+00])

In [10]:
elastic_model.l1_ratio_

1.0

In [11]:
# Elastic Net
elastic_model = regression_analysis.train_elastic_net_cv(l1_ratios=0.25, max_iter=100000)
regression_analysis.display_results(elastic_model, "Elastic Net")


After Elastic Net, we have only 4 non-zero coefficients.


metrics
MAE   0.000857
MSE   0.000002
RMSE  0.001507

In [12]:
elastic_model.coef_

array([0.        , 0.05054029, 0.04954104, 0.06322042, 0.05316552,
       0.        , 0.        ])

When L1-ratio = 1, then we had only 3 none-zero coefficients. Elastic net is completely working as Lasso.
Now, L1-Ratio= 0.25, we have 4 none-zero Coefficents. Elastic net is more towards Ridge Regression.